development:
  adapter: mongodb
  host: localhost
  database: badge_app

test: &TEST
  adapter: mongodb
  host: localhost
  database: badge_app_test

production:
  adapter: mongodb
  host: localhost
  database: badge_app

